### ISSUE TITLE
Total Note Count Shows

### ISSUE THREAD

**Issue by ActuallySamBee** [ozntel/file-explorer-note-count#24]
The total note count no longer shows next to the vault name.

### Debug Info
SYSTEM INFO:
	Obsidian version: v1.6.0
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.2.3
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 17
	Plugins enabled: 17
		1: Kanban v1.5.3
		2: List Callouts v1.2.7
		3: Minimal Theme Settings v7.5.0
		4: Obsidian Columns v1.5.2
		5: Paste image rename v1.6.1
		6: Settings Search v1.3.10
		7: Dataview v0.5.66
		8: Custom Font Loader v1.4.0
		9: Advanced Tables v0.21.0
		10: Discord Rich Presence v1.5.1
		11: File Explorer Note Count v1.2.1
		12: YouHaveBeenStaring v1.2.2
		13: Style Settings v1.0.8
		14: Vault Changelog v0.1.0
		15: Editing Toolbar v2.4.16
		16: Iconize v2.12.0
		17: Excalidraw v2.2.0

**Comment by ozntel** [comment]
As far as I can see, Obsidian removed root folder name from the file explorer and included into the Vault Switch drop-down at the left bottom. I included a new functionality to create a root folder in the file explorer on the fly so that I can attach count. Please update your plugin and enable root folder option from the plugin settings. Thanks
